services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    command: bash -c "service ssh start && tail -f /dev/null"
    networks:
      - hadoop_net
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "19888:19888"
      - "8080:8080"
      - "9000:9000"
    volumes:
      - "C:/Users/pc/Documents/master-isi/s1/big data/hadoop_project:/shared_volume"

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    command: bash -c "service ssh start && tail -f /dev/null"
    networks:
      - hadoop_net
    ports:
      - "8040:8042"

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    command: bash -c "service ssh start && tail -f /dev/null"
    networks:
      - hadoop_net
    ports:
      - "8041:8042"

networks:
  hadoop_net:
    driver: bridge